"""Add AI analysis history table

Revision ID: 0b9290b9b979
Revises: 351514616783
Create Date: 2026-09-12 08:21:17.421287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b9290b9b979'
down_revision = '351514616783'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_analysis_history',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('task_version', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('result_json', sa.JSON(), nullable=False),
    sa.Column('reason_stale', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ai_analysis_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ai_analysis_history_task_id'), ['task_id'], unique=False)
        batch_op.create_index('ix_ai_history_task_version', ['task_id', 'task_version'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_analysis_history', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_history_task_version')
        batch_op.drop_index(batch_op.f('ix_ai_analysis_history_task_id'))

    op.drop_table('ai_analysis_history')
    # ### end Alembic commands ###
