"""Add AI job table

Revision ID: 55f419bbc882
Revises: 36b923afae38
Create Date: 2026-09-12 08:07:27.451701

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55f419bbc882'
down_revision = '36b923afae38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ai_job',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=False),
    sa.Column('task_version_analyzed', sa.Integer(), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['task_id'], ['task.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('ai_job', schema=None) as batch_op:
        batch_op.create_index('ix_ai_job_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ai_job_task_id'), ['task_id'], unique=False)
        batch_op.create_index('ix_ai_job_task_status', ['task_id', 'status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ai_job', schema=None) as batch_op:
        batch_op.drop_index('ix_ai_job_task_status')
        batch_op.drop_index(batch_op.f('ix_ai_job_task_id'))
        batch_op.drop_index('ix_ai_job_status_created')

    op.drop_table('ai_job')
    # ### end Alembic commands ###
